# Generated by Django 5.0 on 2024-01-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegi', '0007_reportcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='date_of_reportcard',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'date_of_reportcard')},
        ),
    ]
