# Generated by Django 5.0 on 2024-01-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegi', '0008_alter_reportcard_date_of_reportcard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='date_of_reportcard',
            field=models.DateField(auto_created=True),
        ),
    ]
