# Generated by Django 5.0 on 2024-01-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegi', '0010_alter_reportcard_date_of_reportcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
