# Generated by Django 5.0 on 2024-01-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegi', '0011_recipe_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
